name: CI Build and Test

on:
  pull_request:
    types: [ opened ]
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler: 'latest'
      - name: Install Shopify CLI
        run: npm install -g @shopify/cli
      - name: Deploy
        env:
          SHOPIFY_FLAG_STORE: '${{ secrets.SHOP_STORE }}'
          SHOPIFY_CLI_THEME_TOKEN: '${{ secrets.SHOP_PASSWORD }}'
          SHOPIFY_CLI_TTY: 0
        run: shopify theme push -d -f --password '${{ secrets.SHOP_STORE }}' --store '${{ secrets.SHOP_STORE }}'
