name: CI Build and Test

on:
  pull_request:
    types: [ opened ]
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Post a comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `# test`;

            console.log(context);
  
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

            
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 18
      # # - name: Install Shopify CLI
      #   run: npm install -g @shopify/cli
      # - name: Deploy
      #   run: shopify theme push -d -f --password ${{ secrets.SHOPIFY_PASSWORD }} --store ${{ secrets.SHOP_STORE }} --verbose
