name: CI Build and Test

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Post a comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const issue_number = context.issue.number;
            const commentBody = "This is a comment from the GitHub Action!";
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: commentBody
            });
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 18
      # # - name: Install Shopify CLI
      #   run: npm install -g @shopify/cli
      # - name: Deploy
      #   run: shopify theme push -d -f --password ${{ secrets.SHOPIFY_PASSWORD }} --store ${{ secrets.SHOP_STORE }} --verbose
