name: CI Build and Test

on:
  pull_request:
    types: [ opened ]
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Shopify CLI
        run: npm install -g @shopify/cli
      - name: Push temporary theme
        run: shopify theme push -d -f --password ${{ secrets.SHOPIFY_PASSWORD }} --store ${{ secrets.SHOP_STORE }} --json
      - name: Read temporary theme URL
        id: parse_output
        run: |
          cat deployment_output.json
          preview_url=$(cat deployment_output.json | jq -r '.theme.preview_url')
          echo "preview_url=${preview_url}" >> $GITHUB_ENV
      - name: Post a comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const preview_url = process.env.PREVIEW_URL;

            if (!preview_url) {
              throw new Error('Preview URL not found.');
            }

            const output = `The theme has been deployed. You can preview it here: ${preview_url}`;
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

            
