name: Theme deploy

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli

      - name: Deploy
        env:
        run: |
          shopify theme push \
            --json \
            --store cheap-comic-strip-com.myshopify.com \
            --password ${{ secrets.SHOPIFY_PASSWORD }}
