name: CI Build and Test

on: [push]
  # pull_request:
  #   types: [ opened ]
  #   branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Shopify CLI
        run: npm install -g @shopify/cli
      - name: Push temporary theme
        run: shopify theme push -d -f --password ${{ secrets.SHOPIFY_PASSWORD }} --store cheap-comic-strip-com.myshopify.com --json > deployment_output.json
      - name: Read temporary theme URL
        id: parse_output
        run: |
          cat deployment_output.json
          preview_url=$(cat deployment_output.json | jq -r '.theme.preview_url')
          editor_url=$(cat deployment_output.json | jq -r '.theme.theme.editor_url')
          echo "PREVIEW_URL=${preview_url}" >> $GITHUB_ENV
          echo "EDITOR_URL=${editor_url}" >> $GITHUB_ENV
      - name: Post a comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const previewUrl = process.env.PREVIEW_URL;
            const editorUrl = process.env.EDITOR_URL;

            if (!previewUrl || !editorUrl) {
              throw new Error('Preview or editor URL not found.');
            }

            const output = `**✨ Your PR is available for preview!**
            - Preview: ${previewUrl}
            - Edit: ${editorUrl}`;
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
