name: Auto update

on:
  push:
    branches:
      - '*'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get PR number
        id: get_pr
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/pulls
          query: |
            head=${{ github.repository_owner }}:${GITHUB_REF##*/}
            state=open
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save PR Number to Environment Variable
        if: ${{ steps.get_pr.outputs.data != '[]' }}
        run: |
          PR_NUMBER=$(echo '${{ steps.get_pr.outputs.data }}' | jq '.[0].number')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Shopify CLI
        run: npm install -g @shopify/cli
      - name: Update theme with the latest commit
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          shopify theme push -t "pr-preview-$branch_name" --password ${{ secrets.SHOPIFY_PASSWORD }} --store cheap-comic-strip-com.myshopify.com
        continue-on-error: true
